### ISSUE TITLE
add a filter for newest to oldest video

### ISSUE THREAD

**Issue by kdpandey09** [matrixiocommunity/Youtube_Scrapper#1]
Issue : - at present the data is sent unordered
solution req :- add an algorithm to filter the data on the basis of publishing date

**Comment by aadityasaini** [comment]
Hello Kaustub, if it's alright with you, I'd like to resolve this issue.

**Comment by aadityasaini** [comment]
Hello Kaustub, if it's alright, I'd like to resolve this issue.

**Comment by kdpandey09** [comment]
> Hello Kaustub, if it's alright, I'd like to resolve this issue.

Sure @aadityasaini go for it
